services:
  db:
    image: postgres:16-alpine
    container_name: rr-cesi-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: rr_cesi
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test -d rr_cesi']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
